### PR TITLE
Collection of fixes

### PR DESCRIPTION
**Pull request by kimocoder**
* Enable USB3 mode switch, this also enables VHT SS3.

### CODE REVIEW

**Comment by kimocoder** [comment]
* Added more "iw link" output
* Added HT Greenfield capabilities
* VHT fixes
* Fix USB3 modeswitch
* Set correct number of hardcoded streams 8812/8821 chipsets

**Comment by kimocoder** [comment]
* Fixed compile warnings (missing brackets)

**Comment by kimocoder** [comment]
* Increased standard txpower from 13 to 18
* Fix interface rename error
* Fix compilation error under kernel v3.13
* Compile on kernel v4.11
* Add support for kernels >= v4.7

* Added get channel function
  Removes fixed channel -1 on airodoump-ng, 
  also it gives information about the current channel to iwconfig and iw.

**Comment by kimocoder** [comment]
Done with the PR. Feel free to evaluate the changes to see if something was done wrong or could be improved somehow :1st_place_medal:

**Comment by fariouche** [comment]
tested with usb3 on my PC, no issues.
Working with 8814 too ;)
